sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: cwz-sky-itcast
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
  wechat:
    appid: wx3317863ee9508c30
    secret: cbb835d2cbe451056cbb4c1ea37c1332
    mch-id: 1649148772
    mch-serial-no: 3C8A7F5B9F6A9F8E8A7F5B9F6A9F8E8A
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url: